FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    cron \
    jq \
    python3 \
    python3-pip \
    && pip3 install requests --break-system-packages \
    && apt-get clean

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
COPY update.sh /usr/local/bin/update.sh
COPY fetch_data.py /usr/local/bin/fetch_data.py

RUN chmod +x /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/update.sh

VOLUME /shared

ENTRYPOINT ["entrypoint.sh"]